### ISSUE TITLE
Fix up CI, including making release builds with different features and variants available as artifacts

### ISSUE THREAD

**Issue by girlbossceo** [girlbossceo/conduwuit#2]
Also might consider removing the Docker stuff, I'm not interested in packaging container stuff unless someone wants to help with that

**Comment by CobaltCause** [comment]
Since #8, there is now CI for:

* rustfmt'ing
* rustdoc lints
* clippy lints
* rust tests

**Comment by girlbossceo** [comment]
Still missing publishing to GitHub Container registry and Docker, and I would like to add additional targets like `x86_64-unknown-linux-musl-sha256-media` so it builds with the `sha256_media` feature but I'm so burnt out from this nix CI stuff so I'll maybe deal with it another time.

All artifacts outputted only have default features. I don't think many people are using sha256_media anyways except for me.

I was also left with no choice but to revert back to latest stable rust-rocksdb because of incredibly frustrating linker issues, but considering they said they would release a new version soon (https://github.com/rust-rocksdb/rust-rocksdb/issues/858#issuecomment-1918976791) I think this is fine as a temporary thing.

As is, it should be working the same as upstream and should be good enough.
