### ISSUE TITLE
Add debug option to retrieve PDU from another server

### ISSUE THREAD

**Issue by tcpipuk** [girlbossceo/conduwuit#211]
Would it be feasible to update the `!admin debug get-pdu` command to accept an optional server on the end to trigger retrieving that PDU from another server?

It'd really help while testing the odd missing PDU I have, but would also help fill gaps in the database when odd things happen.

For example, currently if I run this:

```
!admin debug get-pdu $$LGX4aNj2JJq1g324w-VMQQzhPge99aE95klwMc6BiIA
```

I get "PDU not found." as the response, but if I could run an alternative like this:

```
!admin debug get-pdu $$LGX4aNj2JJq1g324w-VMQQzhPge99aE95klwMc6BiIA example.com
```

Conduwuit would hopefully retrieve that missing event from the example.com server, so I could not only see the content but also it'd fix the gap in my room history.

**Comment by girlbossceo** [comment]
This should now be implemented.

`!admin debug get-remote-pdu <PDU_ID> <SERVER>`

It will treat the remote PDU as an incoming backfilled PDU. Standard event auth checks and if we have the event already is already done.

**Comment by tcpipuk** [comment]
Amazing, thank you!
