### ISSUE TITLE
Switch from the questionable rust-argon2 crate for password hashing to reputable RustCrypto argon2 crate

### ISSUE THREAD

**Issue by girlbossceo** [girlbossceo/conduwuit#22]
[rust-argon2](https://github.com/sru-systems/rust-argon2/) is *okay*, did have some unsoundness (undefined behaviour) that the developer refused to fix for a couple years until recently, but it isn't really actively maintained (issues and few PRs unresponsive, deps rarely updated) overall. Additionally, the upstream default config is absurdly aggressive (they went with the RFC defaults instead of OWASP defaults which are absurdly resource intensive without announcing such drastic change) which is just another reason to use a crate by a developer that doesn't make crazy/breaking changes like that unannounced.

I'm not sure why Conduit went with this crate, maybe RustCrypto argon2 didn't exist at the time? But I'd really like to switch to a reputable argon2 crate: https://github.com/RustCrypto/password-hashes/tree/master/argon2

Performance isn't a concern because this is purely just for hashing passwords and these crates aren't async anyways, but we don't want to use expensive configs either.

Tried making an attempt at making it build but I can't figure it out.

Concerns:
- Database compatibility (do we need database format changes/migrations)
- Existing hash compatibility (will users be logged out when this is changed? can we avoid that? will we need to migrate the existing hashes? etc)

**Comment by CobaltCause** [comment]
> I'm not sure why Conduit went with this crate, maybe RustCrypto argon2 didn't exist at the time?

Highly likely
