### ISSUE TITLE
Recent ruma updates prevent setting up new Mautrix bridges

### ISSUE THREAD

**Issue by mjm** [girlbossceo/conduwuit#221]
I just set up a new Conduit server yesterday using this fork. Today I was trying to set up the mautrix-slack bridge, but after registering its appservice, I was getting forbidden errors when it tried to check for connectivity by hitting the `/_matrix/client/versions` endpoint. This error prevented setting up the bridge.

The error indicates "User does not exist" because this API call is happening before the bridge attempts to register its bot user. It's intended to just check for connectivity to the homeserver and record the supported versions.

Until recently, this endpoint had `AuthScheme::None`, but a [recent change](https://github.com/girlbossceo/ruma/commit/3997e445b5809ccdec017674207d8d0176cec171) in `ruma-client-api` changed it to `AuthScheme::AccessTokenOptional`. That means it now hits [this user ID validation](https://github.com/girlbossceo/conduwuit/blob/930bf3891c5a1279b23e16f3f10ce02c47b9b4cb/src/api/ruma_wrapper/axum.rs#L89-L102) that it wasn't hitting before.

[This commit](https://github.com/girlbossceo/conduwuit/commit/5a15dab7a96459a9ba8a99db7dec636fee306a61) is the one that bumped ruma to a version that changed the auth scheme. By downgrading to the parent commit, I was able to set up my bridge.

**Comment by girlbossceo** [comment]
If you are building yourself, could you try these two commits?

https://github.com/girlbossceo/conduwuit/commit/5421c0858ed62ded40730b17618e0474e63c9d70
https://github.com/girlbossceo/conduwuit/commit/4a62acbcf3dd146f243925c1c12c5e4d3f5d24ec

If you would like to use a static binary (though has pre-release 0.1.8 features), they are here: https://github.com/girlbossceo/conduwuit/actions/runs/8320658572

I don't know much about Appservices but after looking through before and after behaviour, I think this should fix it, and based on my (very poor) testing with mautrix-telegram.

**Comment by mjm** [comment]
Thanks for looking at this so quickly!

I'm using the Nix flake to build it myself, so I can update to that commit. I think I'll need until tomorrow evening to be able to actually test this behavior, since I've already set up my Slack bridge, so it's been able to create its user and won't fail the validation anyway. I'm planning to set up some more bridges though, so I'll try to get another one going tomorrow and see if it works with these changes.

**Comment by girlbossceo** [comment]
@RoootTheFox tested the patches above and reported that it fixes this exact issue. I'll try to merge https://github.com/girlbossceo/conduwuit/pull/220 today.

**Comment by mjm** [comment]
Looks like it fixed it for me too! I set up mautrix-discord. Upon first starting it, before I've had a chance to register it in Conduit, it gets 401 errors because of an unknown access token. Upon registering the appservice, the request succeeds and it's able to proceed to register its bot user. Thanks for the quick fix!

**Comment by girlbossceo** [comment]
Fixed in Conduwuit 0.1.8 now
