### ISSUE TITLE
AppService bridges not able to see my messages with recent change

### ISSUE THREAD

**Issue by mjm** [girlbossceo/conduwuit#240]
The other day I updated from 101cb34f9a1b94b91717af3581f35386f20d4601 to 051668b62b76270dc8ad3b011c6adbfe8ee8bde2, and after doing so, it seems like none of my bridges can see any messages from me. They're still posting their own messages from other people using the bridged service (so incoming Slack, Discord, IRC messages still show up), but anything I'm doing isn't getting seen.

I noticed a message I posted in a bridged Discord channel didn't show up in Discord itself, and then I tried to interact with the bot users of the various bridges and couldn't get them to even respond to a "help" message.

After reverting my server to 101cb34f9a1b94b91717af3581f35386f20d4601, all the messages I had sent before were seen all at once and handled.

**Comment by mjm** [comment]
If I had to guess, could be that https://github.com/girlbossceo/conduwuit/commit/32ab88e68a3fe1c2b0f70d7cc363d6d0a2bf7e8a is the reason?

**Comment by girlbossceo** [comment]
Yes if your Appservice is hosted on the same machine and you have a URL set in your config, it may be blocking localhost requests. See the example config file to remove/set it blank and see if that fixes it.

If it does I'll reevaluate checking that against Appservice URL requests.

**Comment by mjm** [comment]
Ok thanks I'll give it a try and report back.

**Comment by RoblKyogre** [comment]
actually had this issue too, was indeed fixed by setting the ip denylist to be blank

**Comment by mjm** [comment]
I re-updated to the latest version, this time with the default denylist minus the localhost entries, and my bridges are receiving messages. Thanks for the quick response!

**Comment by girlbossceo** [comment]
I've reverted this as this is actually the `url` field of your Appservice registration file which an admin would vet before registering it, and is almost always localhost.

https://github.com/girlbossceo/conduwuit/commit/c8e9591bdba8e938d1cdcfb54aa014d0414536bf
