### ISSUE TITLE
Generate config documentation for use on the website

### ISSUE THREAD

**Issue by girlbossceo** [girlbossceo/conduwuit#3]
There are a ton that are not documented, I also think there's a `workers` config option maybe from one of the HTTP libraries?

Don't think it's that useful though if all the request stuff is on the main tokio runtime either way.

**Comment by CobaltCause** [comment]
One way to do this is to generate and make available a JSON Schema document that describes the configuration file via [`schemars`](https://docs.rs/schemars). This way, the documentation is generated from the code, which helps make sure the documentation doesn't become stale.

**Comment by girlbossceo** [comment]
I believe this is completed at this point. A better way to do it like mentioned above is still an option for the future, but currently the `conduwuit-example.toml` file has about 95% of the available config options and is kept up to date on new additions.

**Comment by girlbossceo** [comment]
Bringing this back as I'd like to get our config options documented on the website through some form of config generation / schema (see above using `schemars`), but I do *not* want to maintain two sets of documentations.

**Comment by girlbossceo** [comment]
We now generate our example config through a build-time proc-macro, parsing the comments in `src/core/config/mod.rs`, and automatically writes to `conduwuit-example.toml`. Further technical details about how it works may be documented on the website soon.
