### ISSUE TITLE
admin bot still mentions  `disable-room` as valid command

### ISSUE THREAD

**Issue by nabulator** [girlbossceo/conduwuit#323]
https://github.com/girlbossceo/conduwuit/blob/341bafb91e77cd95775d9cfa4f0810309889b176/src/service/admin/room/room_moderation_commands.rs#L172

Upon banning a room, a help message suggesting the possibility of running `disable-room` to stop receiving inbound federation event. However no such command exists.

Has the `disable-room` command been renamed here? I tried joining matrix HQ chat and my error logs are tell me the room has no state so trying to stop those errors somehow.

**Comment by girlbossceo** [comment]
It's under `!admin federation disable-room`, I can see how that message can be confusing. I'll make it clear it's under `!admin federation` in that message

**Comment by nabulator** [comment]
ah thanks for the quick response! I somehow missed the command in my search.

**Comment by girlbossceo** [comment]
This message's wording was fixed
