### ISSUE TITLE
Panics while setting socket permissions 

### ISSUE THREAD

**Issue by nisbet-hubbard** [girlbossceo/conduwuit#335]
Thanks for creating an alternative to Conduit!
```
May  4 13:30:46 conduwuit[1332858]: thread 'main' panicked at src/main.rs:204:10:
May  4 13:30:46 conduwuit[1332858]: called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" } 
```
What is happening here appears to be while `tokio::fs::remove_file` worked fine, `tokio::fs::create_dir_all` didn’t create the socket file so `tokio::fs::set_permissions` couldn’t find it.

What can I do to troubleshoot this?

**Comment by girlbossceo** [comment]
UNIX socket support has been broken for a couple weeks now post-Hyper v1 upgrade and I haven't been able to figure it out. I probably should have made it more clear it's non-functional at the moment, but hopefully by the next release I can get it figured out and fixed.

**Comment by girlbossceo** [comment]
UNIX sockets have been fixed and are functional again in `main` branch, a release will come later with the fix
