### ISSUE TITLE
Feature: stop sending sync events from ignored users

### ISSUE THREAD

**Issue by Benjamin-L** [girlbossceo/conduwuit#349]
Currently, our only server-side support for ignored users is that we drop any invite requests from a ignored user. According to [the spec](https://spec.matrix.org/v1.10/client-server-api/#mignored_user_list), we should stop sending non-state events from ignored users on sync. We don't do this yet, which causes ignoring to not work correctly (to varying degrees) on clients.

On cinny, messageses from ignored users still show up in the UI. On element web, it seems that the implementation of retroactively hiding already-synced events from ignored users also hides events that we are (incorrectly) syncing, but element web users still receive notifications from ignore user's messages.

**Comment by jevolk** [comment]
Just noting this should cover ephemeral events as part of that definition for non-state events if it isn't implied.

**Comment by girlbossceo** [comment]
This is now implemented for EDUs (read receipts and typing indicators), messages, invites, etc over /sync, sliding sync, /context, and /messages.
