### ISSUE TITLE
Document ‘nocanon’ for httpd

### ISSUE THREAD

**Issue by nisbet-hubbard** [girlbossceo/conduwuit#401]
Currently, the requirement is shown as an error message when it’s not set: https://github.com/girlbossceo/conduwuit/blob/f3427afc7fc7a0e67a8c78be24cba898a6bdba2e/src/api/ruma_wrapper/axum.rs#L245-L246

So perhaps we should mention it somewhere in the docs? There’s also small performance gains to be made by tweaking the example config for Apache httpd over at Conduit.

**Comment by girlbossceo** [comment]
I would rather just add a small note somewhere making it generic instead of making it Apache-specific.

> "Please make sure your reverse proxy gives conduwuit the raw, original request URI."

This way I'm not adding extra reverse proxy "examples" which was something we intentionally removed for many reasons.

**Comment by girlbossceo** [comment]
I don't see how or why these would impact performance.

**Comment by girlbossceo** [comment]
I think your config should just be left as default + `nocanon`. Is there an issue or something you're facing that you're finding yourself modify these reverse proxy config options?

**Comment by girlbossceo** [comment]
> I was just puzzled by these additional settings I saw in Conduit's example.

This is most certainly one of the many reasons why conduwuit deleted all these reverse proxy examples and urges the user to find documentation online on setting up a reverse proxy, with us providing generic instructions, and generally leave things at their defaults.

They become very opinionated, confusing (as you just mentioned), are annoying to maintain, etc.
