### ISSUE TITLE
Listen on both IPv4 and IPv6

### ISSUE THREAD

**Issue by piegamesde** [girlbossceo/conduwuit#404]
I am constantly seeing "connection refused" errors from nginx trying to reach conduwuit. They happen up to several times a minute upon client activity, yet it does not appear to affect overall usage and functionality. (Some things are broken as usual, but I have no idea whether they may be related or not)

```
nginx: [error]: *15000 connect() failed (111: Connection refused) while connecting to upstream, client: …, server: …, request: "GET /_matrix/client/v3/sync?filter=gnsN&timeout=30000&set_presence=online&since=36275 HTTP/2.0", upstream: "http://127.0.0.1:6167/_matrix/client/v3/sync?filter=gnsN&timeout=30000&set_presence=online&since=36275", host: "…"
```

My nginx config (within NixOS):

```
      locations."/_matrix/" = {
        proxyPass = "http://localhost:6167";

        proxyWebsockets = true;
        extraConfig = ''
          proxy_set_header Host $host;
          proxy_buffering off;
        '';
      };
```

In the conduwuit log, there are no log messages which would correlate in time with the nginx errors.

**Comment by piegamesde** [comment]
Looking at the logs, it is both the `GET /_matrix/client/v3/sync`, `OPTIONS /_matrix/client/v3/sync` and `PUT /_matrix/federation/v1/send` which are affected. I assume that they are working most of the time and that clients simply retry and then it works, otherwise a lot more would be broken.

**Comment by CobaltCause** [comment]
NGINX listening on localhost instead of an IP literal is suspicious. What do you have `services.matrix-conduit.settings.global.address` set to? Try making your NGINX config match that address instead of using `localhost` and see if that fixes it.

**Comment by girlbossceo** [comment]
Check what conduwuit is listening on: `ss -tulpn | grep -i cond`

Use that as your nginx proxy pass instead of `localhost`.

**Comment by piegamesde** [comment]
Interesting, I was pretty sure having tried that in the past and it didn't work, but now that indeed resolves the issue. Moreover, it also works with `::1` on both sides.

So as far as I understand it `localhost` resolves to the correct address, but is ambiguous as to which IP protocol to use. Nginx seems to use IPv4 and IPv6 at will, which then causes the failure in the other case, respectively.

So the ideal fix would be to have Conduwuit listen to both IPv4 and IPv6 by default, to eliminate the foot gun entirely. AFAIU this should already be the case simply listening to `::1` because on Linux IPv6 sockets are not exclusive to IPv6, not sure why it didn't work for me in my test.

**Comment by girlbossceo** [comment]
Can add support for listening on multiple addresses

**Comment by piegamesde** [comment]
About the implementation, is it correct that the main thing to do is to modify https://github.com/girlbossceo/conduwuit/blob/main/src/core/config/mod.rs#L473 to be the cartesian product of all ports and addresses?

**Comment by girlbossceo** [comment]
As far as I can tell yes. Similar to the port config option of using Either so we don't break existing configs with `address = "1.2.3.4"` and still allow `address = [1.2.3.4, 5.6.7.8]`, and just making that code aware of multiple addresses and multiple ports.

Also, after a quick discussion in the conduwuit Matrix room, I'll change the default `address` to listen on IPv6 `[::1]` as this is dual stack by default on Linux unlike IPv4 `127.0.0.1`. Listening on multiple addresses will just be a small extra feature.

**Comment by girlbossceo** [comment]
Listening on multiple addresses and multiple ports are now supported, and it is configured to default listen on both IPv4 localhost (`127.0.0.1`) and IPv6 localhost (`[::1]`).
