### ISSUE TITLE
Implement extended user profiles for MSC4133 (Done)

### ISSUE THREAD

**Issue by tcpipuk** [girlbossceo/conduwuit#435]
Work on [MSC4133](https://github.com/matrix-org/matrix-spec-proposals/pull/4133) has progressed quite far, and looks unlikely to change significantly now - would you be happy to consider an unstable implementation in conduwuit to help push this MSC forward?

**Comment by tcpipuk** [comment]
Following extended discussion over the past month or two, I believe this has now reached a solid position where any further changes are likely to be clarifications only.

In the meantime, Patrick has kindly prepared a partial implementation for Synapse here: https://github.com/element-hq/synapse/pull/17488

**Comment by tcpipuk** [comment]
There's been further movement in [MSC4133](https://github.com/matrix-org/matrix-spec-proposals/pull/4133) so I'm hoping it will be entering FCP soon.

I've got a list of implementations at the top of the MSC - we've got a functioning client implementation, and a partial server implementation, so it'd be grand if we could get an implementation in ruma and/or conduwuit to match 💜

**Comment by girlbossceo** [comment]
This has been implemented in https://github.com/girlbossceo/conduwuit/pull/571 which is available in our main branch and will be in the next tagged release.

We don't support PATCH at the moment, but GET/PUT/DELETE are implemented.

**Comment by tcpipuk** [comment]
Thank you kindly!

**Comment by tcpipuk** [comment]
Actually, @girlbossceo it might be worth keeping an issue open for the remainder of [MSC4133](https://github.com/matrix-org/matrix-spec-proposals/pull/4133)? I assume Ruma's going to get it sooner or later, but it'd need implementation.

**Comment by girlbossceo** [comment]
Leaving open until MSC4133 is merged

**Comment by girlbossceo** [comment]
I'm going to close this as I was under the impression that the overall Matrix community would see the value in MSC4133 and guarantee a swift process and merge, but that doesn't seem to be the case anymore.

I'm still going to make sure MSC4133 and such continue to work on conduwuit, but I'm going to close this as resolved.

**Comment by tcpipuk** [comment]
Sorry @girlbossceo - MSC4133 is waiting for me to tweak some bits, but I've had to pivot to completing some other projects. I'm planning for another push later this month, but adoption will be slow until I'm done so Patrick can finish the Synapse implementation 😢
