### ISSUE TITLE
cargo build failed

### ISSUE THREAD

**Issue by mikehjc** [girlbossceo/conduwuit#444]
1) uname -a
FreeBSD build-jail 14.0-CURRENT FreeBSD 14.0-CURRENT amd64 1400094: Sat May 25 06:23:23 UTC 2024

2) Installed package
pkg install -y rust git-lite ca_root_nss llvm15
~
clang -v
FreeBSD clang version 16.0.6 (https://github.com/llvm/llvm-project.git llvmorg-16.0.6-0-g7cbf1a259152)
Target: x86_64-unknown-freebsd14.0
Thread model: posix
InstalledDir: /usr/bin
~
pkg info rust
rust-1.78.0
Name           : rust
Version        : 1.78.0
Installed on   : Sun Jun  9 18:36:30 2024 +07
Origin         : lang/rust
Architecture   : FreeBSD:14:amd64
Prefix         : /usr/local
Categories     : lang
Licenses       : MIT or APACHE20
Maintainer     : rust@FreeBSD.org
WWW            : https://www.rust-lang.org/
Comment        : Language with a focus on memory safety and concurrency
Options        :
        DOCS           : on
        GDB            : off
        LTO            : off
        PORT_LLVM      : off
        SOURCES        : on
        WASM           : on
Shared Libs required:
        libcurl.so.4
Annotations    :
        FreeBSD_version: 1400097
        build_timestamp: 2024-05-30T01:07:37+0000
        built_by       : poudriere-git-3.4.1-30-g79e3edcd
        cpe            : cpe:2.3:a:rust-lang:rust:1.78.0:::::freebsd14:x64
        port_checkout_unclean: no
        port_git_hash  : a40e26254
        ports_top_checkout_unclean: no
        ports_top_git_hash: 02faf78f4
        repo_type      : binary
        repository     : FreeBSD

3) Build command:
Version="0.4.1"
fetch https://github.com/girlbossceo/conduwuit/archive/refs/tags/v$Version.tar.gz
tar -xvf v$Version.tar.gz && rm v$Version.tar.gz && mv conduwuit-$Version conduwuit
~
cd conduwuit
export RUSTUP_TOOLCHAIN=stable
export CARGO_TARGET_DIR=target
cargo fetch
cargo build --release --verbose &> build.log

4) Error log
tail -10  build.log

  exit status: 0

  --- stderr

  error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-stdlib=libc++" "--target=x86_64-unknown-freebsd" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "/root/conduwuit/target/release/build/lz4-sys-2524ef88bbc4d6fc/out/include" "-I" "/root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zstd-sys-2.0.10+zstd.1.5.6/zstd/lib" "-I" "/root/conduwuit/target/release/build/libz-sys-93860f7d54e98295/out/include" "-I" "/root/conduwuit/target/release/build/bzip2-sys-13423a686cbfc105/out/include" "-I" "." "-I" "/root/conduwuit/target/release/build/tikv-jemalloc-sys-6deccb9157cbbb4a/out/include" "-Wall" "-Wextra" "-std=c++17" "-Wsign-compare" "-Wshadow" "-Wno-unused-parameter" "-Wno-unused-variable" "-Woverloaded-virtual" "-Wnon-virtual-dtor" "-Wno-missing-field-initializers" "-Wno-strict-aliasing" "-Wno-invalid-offsetof" "-msse2" "-std=c++17" "-DSNAPPY=1" "-DLZ4=1" "-DZSTD=1" "-DZLIB=1" "-DBZIP2=1" "-DNDEBUG=1" "-DOS_FREEBSD" "-DROCKSDB_PLATFORM_POSIX" "-DROCKSDB_LIB_IO_POSIX" "-DROCKSDB_SUPPORT_THREAD_LOCAL" "-DROCKSDB_JEMALLOC=1" "-DJEMALLOC_NO_DEMANGLE=1" "-o" "/root/conduwuit/target/release/build/rust-librocksdb-sys-03b2d0b13bd7a600/out/8f2beba317b0d6d5-memory_allocator.o" "-c" "rocksdb/memory/memory_allocator.cc" with args c++ did not execute successfully (status code exit status: 1).

5) You can find the full log here:
https://pastebin.com/afPWp6n2

**Comment by girlbossceo** [comment]
Can you try building from the latest main branch? If that doesn't work, I'm aware of some FreeBSD and jemalloc building issues. In that case, you need to remove `jemalloc` as a default build feature.

**Comment by mikehjc** [comment]
1).After removing jemalloc from all Cargo.toml and engage.toml, It successful build.
My successful build on freebsd: 
https://github.com/mikehjc/conduwuit/releases/tag/v0.4.1

2).The change I made.
https://github.com/girlbossceo/conduwuit/compare/main...mikehjc:conduwuit:main

Thank you for the assist.

**Comment by mikehjc** [comment]
However, when I try to run conduwuit with unix_socket_path,
It failed to start,
setting the config to address mode runs fine.

Here are the logs with BACKTRACE:
2024-06-10T19:49:51.641661Z  INFO conduit::server: 0.4.1 server_name=matrix.example.com database_path="/var/db/conduit" log_levels=info
2024-06-10T19:49:51.699206Z  INFO start: conduit_database::rocksdb: Opened database at sequence number 80154 in 57.278376ms
2024-06-10T19:49:51.710203Z  INFO start: conduit_service::globals::migrations: Loaded rocksdb database with schema version 13
thread 'main' panicked at src/router/serve.rs:131:10:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:     0x1650a67e72ca - <unknown>
   1:     0x1650a62100cc - <unknown>
   2:     0x1650a67d460e - <unknown>
   3:     0x1650a67e7044 - <unknown>
   4:     0x1650a67de197 - <unknown>
   5:     0x1650a67dde98 - <unknown>
   6:     0x1650a67de58a - <unknown>
   7:     0x1650a67e7832 - <unknown>
   8:     0x1650a67e74f6 - <unknown>
   9:     0x1650a67de2a4 - <unknown>
  10:     0x1650a4da8e25 - <unknown>
  11:     0x1650a4da9323 - <unknown>
  12:     0x1650a5cd36d0 - <unknown>
  13:     0x1650a5ccf7a2 - <unknown>
  14:     0x1650a5d56eb8 - <unknown>
  15:     0x1650a4f0ddcf - <unknown>
  16:     0x1650a4ee1028 - <unknown>
  17:     0x1650a4f0f8dd - <unknown>
  18:     0x1650a4ed8a7f - <unknown>
  19:     0x1650a4ef9686 - <unknown>
  20:     0x1650a4f08da5 - <unknown>
  21:     0x1650a67bf075 - <unknown>
  22:     0x1650a4ed8cc5 - <unknown>
  23:     0x1658cb398afa - __libc_start1
  24:     0x1650a4dd915d - <unknown>

**Comment by girlbossceo** [comment]
An upcoming release for 0.4.2 (currently main branch) fixed UNIX sockets.
