### ISSUE TITLE
Unable to fetch remote authenticated media from unauthenticated c2s endpoints

### ISSUE THREAD

**Issue by tusooa** [girlbossceo/conduwuit#586]
If my understanding of the code is right, the problem lies in https://github.com/girlbossceo/conduwuit/blob/main/src/api/client/media_legacy.rs#L150C4-L150C76 , which will only request the remote unauthenticated s2s endpoint before trying the authenticated endpoint, if the c2s request is coming from the unauthenticated endpoint.

**Comment by jevolk** [comment]
This is intended behavior. If the client is not authenticated it doesn't enjoy authenticated media.

**Comment by girlbossceo** [comment]
Yes this is expected. Fetching authenticated media over unauthenticated endpoints would be a security issue.

Is there something you're running into that's causing this concern?

**Comment by tusooa** [comment]
> Yes this is expected. Fetching authenticated media over unauthenticated endpoints would be a security issue.
> 
> Is there something you're running into that's causing this concern?

I'm using a client that does not yet support authenticated media, and all matrix.org media won't load. It seems weird that federation is not transparent through csapi.

**Comment by girlbossceo** [comment]
I do agree it is an unfortunate state of things that pretty much none of this is transparent and older clients, most specifically SchildiChat which is still a perfectly good client, are basically unusable now because this is not transparent. But it may likely upset a lot of folks or cause security issues/concerns if we made this transparent on the server-side and I don't want to step into that territory.

**Comment by tusooa** [comment]
I use the following Caddyfile to reverse-proxy unauthenticated media to authenticated endpoints.

First, create a user and login via a session. Get the access token.

```
server.domain {
  @unauthenticatedMedia {
    expression method('GET', 'HEAD', 'OPTIONS')
    path_regexp ^/_matrix/media/v3/download/([^/]+/[^/]+(/[^/]+)?)$
  }
  reverse_proxy @unauthenticatedMedia localhost:6167 {
    header_up Authorization "Bearer ACCESS-TOKEN"
    rewrite /_matrix/client/v1/media/download/{re.1}
  }
  reverse_proxy localhost:6167
}
```

**Comment by girlbossceo** [comment]
I'll consider this resolved then and leave this issue here for historical/informational purposes. While it is a sad situation, we can't safely make this transparent without stirring up a bunch of issues and concerns.
