### ISSUE TITLE
Document conduwuit's changes from upstream

### ISSUE THREAD

**Issue by girlbossceo** [girlbossceo/conduwuit#6]

**Comment by Sythelux** [comment]
Hi, sorry to use this ticket for the following question, but it was the closest that works. I was wondering it you'll ever push the changes back to upstream or if there was a reason not to except the one that you made big reworks and the codebase probably changed to much.

**Comment by tcpipuk** [comment]
@Sythelux I know it seems like a polite request, but trolling git issues is not the best way to ask why a hard fork is not a soft fork.

Besides the PRs not being accepted in the first place, you've already recognised a huge portion of the codebase has been completely relinted/refactored/rewritten. There are hundreds of commits, and literally thousands of lines changed.

We haven't changed the license - Timo would be welcome to cherrypick changes from conduwuit, but I'd personally recommend if people want to run conduwuit that they're probably better off running conduwuit: it's a public project with responsive support rooms and a team that's actively developing new features, fixing bugs, and improving performance and security.

**Comment by Sythelux** [comment]
This was really not meant as a troll and was a genuine question. I just did not see any mention of it being a hard fork or what the issue is not merging it up except for the obvious reasons.

I gladly take your explanations and will try conduwuit as I also had issues with hosting conduit in the past and have hopes that this works better.

I apologize as I should've mailed instead of posting it on an open issue tracker.

**Comment by tcpipuk** [comment]
You're very welcome to visit our rooms (e.g. [#conduwuit](https://matrix.to/#/%23conduwuit:puppygock.gay)) which are designed for support and questions.

We support a large number of people trying out conduwuit, especially people coming from Conduit, as it's database compatible.

We've made a number of design choices (hopefully for the better!) to add lots of admin room commands and config options, but it would be presumptuous to push those back upstream to Timo's project when he's also making the server the way he wants to as well.

Genuinely, we love extra faces, and I hope you'll find the hundreds of people in our community helpful and welcoming. It's the foundation this whole fork is built on.
