### ISSUE TITLE
Conduit and conduwuit has a rare chance of sending duplicate events over /sync

### ISSUE THREAD

**Issue by girlbossceo** [girlbossceo/conduwuit#606]
This is not really confirmed because there hasn't been a clear reproduction method, no one's provided any /sync responses showcasing the issue or where the events are being erroneously sent twice, and the reports of this issue are from only a couple users who generally have issues with their homeserver that aren't affecting anyone else.

But it's supposedly a problem in some things like maubots.

**Comment by girlbossceo** [comment]
For the record, this appears to be an upstream issue too.

https://gitlab.com/famedly/conduit/-/issues/180

**Comment by girlbossceo** [comment]
It's been confirmed so not really sure, someone needs to work on solving it.

**Comment by nexy7574** [comment]
I wrote a [gist](https://gist.github.com/nexy7574/47475a4d0a0847c12757d932195d85f5) with my findings and a script to repro it, in case it helps anyone with debugging.

**Comment by nexy7574** [comment]
I can confirm that @jevolk's patch (https://github.com/jevolk/conduwuit/commit/b81211c0b6fc7c332052cae35e3dd61ab390b54f) resolves this issue.

**Comment by girlbossceo** [comment]
Fixed/merged in main branch
