### ISSUE TITLE
appservice sending seems to stall sometimes for hours

### ISSUE THREAD

**Issue by fingon** [girlbossceo/conduwuit#611]
Problem: 

Messages to Signal show up sometimes (perhaps once every two, three weeks) with significant delay (hours+).

Version: docker `latest` tag.

I originally blamed Mautrix-Signal (where it seems to be happening most commonly for me), as described in https://github.com/mautrix/signal/issues/561.

But following sequence of events today (and lack of buffering in mautrix-signal) caused me to open this ticket too:
- the messages I sent were missing (visible in Matrix clients, not in Signal)
- restarting the appservice (bridge) did nothing
- restarting the conduwuit caused messages to wind up in appservice, and subsequently Signal clients

**Comment by girlbossceo** [comment]
Just to be sure, you're 100% confident that restarting conduwuit "clears the backlog"?

Because something we inherited from Conduit was this suspicious code that performs exponential backoff on appservice URL sending if there are issues reaching the appservice connecction URL. And I don't understand why one would want to perform exponential backoff on an appservice, because [it does cause problems.](https://gitlab.com/famedly/conduit/-/issues/335)

So as long as you can repeatedly reproduce that restarting conduwuit does fully clear the stuck messages, I think we can just delete exponential backoff for appservices.

**Comment by fingon** [comment]
This happens once every few weeks (reason: unknown) but at least in this one case messages did pop up immediately after Conduwuit was restarted. If there is some log message that would be helpful I could look it up, but I get quite a bit of conduwuit logging in general.

Before the restart of both Signal bridge and Conduwuit, there were two log messages like this spaced ~20 minutes apart:

```
sender:appservice{id="signal"}: conduit_service::sending::appservice: Could not send request to appservice "signal" at http://fw.lan:19328: error sending request for url (http://fw.lan:19328/_matrix/app/v1/transactions/...)
```

Oddly enough, there was also similar message about slack appservice at same time.

It is possible that as I did not wait very long (minute or two?) between restarting appservice and Conduwuit, that the  appservice started actually listening properly and it was really result of appservice being restarted that fixed the problem and the slow backoff causing me to suspect Conduwuit for it.

It is curious though that two different appservices, it started at ~13+ (when the Signal 'buffering' event started) for both Slack and Signal, and cleared at ~14 when I restarted them both.

<img width="1093" alt="Screenshot 2024-11-05 at 17 53 25" src="https://github.com/user-attachments/assets/0699cab6-2a57-4c4b-bc55-7b23d0209756">

Another interesting datapoint is that at 10 o'clock (roughly), both signal and slack experienced one blip of ^ log message but went ahead fine after that (I didn't notice it).

**Comment by fingon** [comment]
Usually I have not done restarts and it has recovered on its own, but it has taken usually couple of hours (no idea why); my bridges and Conduwuit have usually quite high uptime (Signal one was at 2 week uptime, Slack is still at 12 days, and Conduwuit container was probably up a month or so before this restart).

**Comment by girlbossceo** [comment]
Most likely exponential backoff is kicking in when you see an error message log like that.

Does this issue happen consistently when you see that log? Or is this just randomly the appservice will have long delays with messages?

Regardless I think us deleting the silly exponential backoff code for appservices may be a good start.

**Comment by fingon** [comment]
The log is much more common than the delays I notice but of course most of the time I do not look at signal client to see when my messages are delivered. The log message seems to be printed couple of times a day for slack and signal bridges, but not for other app services ( no idea why ). 

I use Slack very seldom now so it might be also doing the same thing. I vaguely remember some similar delayed send episode from months ago with it.

**Comment by girlbossceo** [comment]
If you would like to, could you please test and see if the issue still persists on `main` branch?

**Comment by fingon** [comment]
I switched to main; I'll know in practice probably not very soon (as I don't notice the lag usually that often) but at least the log pattern I can tell about in a day or two.

**Comment by girlbossceo** [comment]
Have you noticed an improvement?

**Comment by fingon** [comment]
It is hard to measure. The rate of those messages in log is perhaps slightly less, but they still appear (no idea why appservice communication on same host would fail). 

I have not seen the user-visible lag yet, though, I think I'll just close this for now, and reopen if it happens again.

**Comment by girlbossceo** [comment]
I think us adding the exclusion for appservices on exponential backoff has solved it then, if you said you observe appservice URL sending failures in your logs, but no user-visible lag is noticeable.

Appservice URL sending failures would cause exponential backoff to kick in and start to delay sending requests to your appservice, and then definitely the user-visible lag would show up.

As for why you are seeing those logs in the first place; they are indicative of a network or host issue of some kind. Unfortunately the HTTP Rust libraries we use don't let us pull the real error message (TCP error? DNS error? I/O error? etc) unless you use a debug build of conduwuit, or build with debug info (`release-debuginfo`), and grep your logs for the host. It might be good to check your appservice's logs itself too and see if it says anything possibly related.
