### ISSUE TITLE
get a promblem when starting conduwuit using systemctl and the default systemd service file

### ISSUE THREAD

**Issue by BKLRsk** [girlbossceo/conduwuit#612]
OS: Debian GNU/Linux trixie trixie/sid x86_64
Kernel: Linux 6.11.2-amd64
Memory: 1015.05 MiB / 1.93 GiB
Swap: Disabled

Conduwuit Version: v0.4.6 [x86_64-unknown-linux-musl.deb](https://github.com/girlbossceo/conduwuit/releases/download/v0.4.6/x86_64-unknown-linux-musl.deb)

After configuring conduwuit porperly, I used "systemctl start conduwuit.service" to launch it but it failed.
Then I used "journalctl /usr/sbin/conduwuit" and it displayed "conduwuit[342665]: memory allocation of 368 bytes failed".
But when I login as root and exec "CONDUWUIT_CONFIG=/etc/conduwuit/conduwuit.toml conduwuit", it just works porperly.
I'm confused that what happened exactly and how to fix it.

So many THANKS!!!

**Comment by girlbossceo** [comment]
Does editing the systemd unit and removing `ProcSubset=pid` solve the issue? Someone identified that this was the problematic flag that seems to break Rust itself (?) with heap memory allocations.

**Comment by BKLRsk** [comment]
yes. it works! thank you
hope systemd may fix this problem
