### ISSUE TITLE
Config option to require authentication for profile requests, and disable profile lookup requests over federation (?)

### ISSUE THREAD

**Issue by girlbossceo** [girlbossceo/conduwuit#82]
`require_auth_for_profile_requests` and `allow_profile_lookup_over_federation` in Synapse

https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#require_auth_for_profile_requests
https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#allow_profile_lookup_over_federation

https://github.com/element-hq/synapse/blob/4e4a0f79b9a8156d4feec8c414063b0f8ba565d7/synapse/rest/client/profile.py#L70

Trying to understand the use-case for disabling `allow_profile_lookup_over_federation` since at that point you should just disable federation, but certain endpoints requiring authentication is certainly useful.

**Comment by girlbossceo** [comment]
Element doesn't send `Authorization` either so I don't quite know why it's in Synapse if it requires a patched client to send authentication. Just moving this to no priority then.

**Comment by morguldir** [comment]
> Element doesn't send `Authorization` either so I don't quite know why it's in Synapse if it requires a patched client to send authentication. Just moving this to no priority then.

Seems like it does :thinking: https://github.com/matrix-org/matrix-js-sdk/blob/b842192a3415dbe91c8a5d13ae7c0fa2b8c239ad/src/client.ts#L8813-L8821

> Trying to understand the use-case for disabling allow_profile_lookup_over_federation since at that point you should just disable federation, but certain endpoints requiring authentication is certainly useful.

On my synapse i have some users that aren't federated (unless they want to), and they have pseudonymous usernames, but sometimes their display name isn't anonymous, so if i allowed profile lookups without limitation, then they could dox all of my users with a spider or something :crying_cat_face:

**Comment by girlbossceo** [comment]
These 2 config options should now be implemented.
